AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  prueba_stori
  
  Sample SAM Template for prueba_stori

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  StorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: prueba-stori-bucket
  ProcessFileFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: process_file
      CodeUri: cmd/process_transactions
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Policies:
        - S3ReadPolicy:
            BucketName: prueba-stori-bucket
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ses:SendTemplatedEmail
                - ses:SendEmail
                - ses:SendRawEmail
                - ses:GetTemplate
                - ses:ListIdentities
              Resource: "*"
      Events:
        s3UploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref StorageBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .csv