name: CI/CD for Stori Test Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup AWS CLI Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Mockery
        uses: brokeyourbike/go-mockery-action@v0
        with:
          mockery-version: '2.45.0' # The mockery version to download and use.
      - name: Check coverage
        run: |
          make gen-mocks
          make check-coverage
      - name: Build and deploy
        run: |
          make deploy
